# Generated by Django 2.2.3 on 2019-07-28 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopProduct',
            fields=[
                ('warehouseproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='warehouse_app.WarehouseProduct')),
            ],
            bases=('warehouse_app.warehouseproduct',),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True)),
                ('is_active', models.BooleanField()),
                ('is_valid', models.BooleanField()),
                ('is_canceled', models.BooleanField()),
                ('is_stoped', models.BooleanField()),
                ('basket', models.ManyToManyField(blank=True, default=None, to='shop_app.ShopProduct', verbose_name='Корзина')),
                ('customer', models.ForeignKey(on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
