# Generated by Django 2.2.3 on 2019-07-28 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopproduct',
            options={'verbose_name': 'shop product', 'verbose_name_plural': 'shop products'},
        ),
    ]
