# Generated by Django 2.2.3 on 2019-07-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_auto_20190728_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='full_price',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Итоговая стоимость'),
        ),
    ]
