# Generated by Django 2.2.3 on 2019-07-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0004_order_full_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True)),
                ('amount', models.FloatField(blank=True, default=None, null=True, verbose_name='Итоговая стоимость')),
            ],
            options={
                'verbose_name': 'promotion',
                'verbose_name_plural': 'promotions',
            },
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'order', 'verbose_name_plural': 'orders'},
        ),
        migrations.AlterModelOptions(
            name='shopproduct',
            options={'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='promotions',
            field=models.ManyToManyField(blank=True, default=None, to='shop_app.Promotion', verbose_name='Акции'),
        ),
    ]
