# Generated by Django 2.2.3 on 2019-07-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0006_auto_20190728_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='amount',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='promotion %'),
        ),
    ]
