# Generated by Django 2.2.3 on 2019-07-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True)),
                ('_type', models.CharField(blank=True, choices=[('banana', 'Banana'), ('apple', 'Apple'), ('orange', 'Orange')], db_index=True, default=None, max_length=255, null=True)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('in_stock', models.BooleanField()),
            ],
        ),
    ]
