# Generated by Django 2.2.3 on 2019-07-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_app', '0002_auto_20190728_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseproduct',
            name='_article',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True),
        ),
    ]
