# Generated by Django 2.2.3 on 2019-07-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_app', '0003_warehouseproduct__article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseproduct',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
    ]
