# Generated by Django 2.2.3 on 2019-07-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_app', '0004_auto_20190728_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseproduct',
            name='price',
            field=models.FloatField(),
        ),
    ]
