# Generated by Django 2.2.3 on 2019-07-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_app', '0005_auto_20190728_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseproduct',
            name='_type',
            field=models.CharField(blank=True, choices=[('banana', 'Banana'), ('apple', 'Apple'), ('orange', 'Orange')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='warehouseproduct',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='warehouseproduct',
            name='price',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
