# Generated by Django 2.2.3 on 2019-07-28 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_app', '0006_auto_20190728_1717'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehouseproduct',
            options={'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
    ]
